import argparse
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

parser = argparse.ArgumentParser(description="Plot Schwarzschild constraint magnitudes vs radius")
parser.add_argument("csv", nargs="?", default="schwarzschild_constraints.csv",
                    help="CSV file generated by the schwarzschild constraint export test")
args = parser.parse_args()

df = pd.read_csv(args.csv)
if 'r' not in df.columns:
    r = np.sqrt(df['x']**2 + df['y']**2 + df['z']**2)
    df['r'] = r
else:
    r = df['r'].to_numpy()

def scatter_constraint(series, label):
    eps = 1e-18
    ax.scatter(r, np.maximum(np.abs(series), eps), s=6, label=label)

fig, ax = plt.subplots(figsize=(8, 5))
scatter_constraint(df['H'], '|H|')

m_mag_col = 'M_mag' if 'M_mag' in df.columns else ('M' if 'M' in df.columns else None)
if m_mag_col is not None:
    scatter_constraint(df[m_mag_col], '|M|')

c_mag_col = 'C_mag' if 'C_mag' in df.columns else ('C' if 'C' in df.columns else None)
if c_mag_col is not None:
    scatter_constraint(df[c_mag_col], '|C|')
ax.set_yscale('log')
ax.set_xlabel('r')
ax.set_ylabel('Constraint magnitude')
ax.set_title('Schwarzschild isotropic constraints')
ax.legend()
plt.tight_layout()
plt.show()
