from typing import List, Tuple

class Vector:
    def __init__(self, data: List[float]) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, idx: int) -> float: ...
    def print(self) -> None: ...

class Vectord(Vector):
    ...
    
class Matrix:
    rows: int
    cols: int
    def __init__(self, rows: int, cols: int) -> None: ...
    def fill(self, values: List[List[float]]) -> None: ...
    def print(self) -> None: ...
    def __getitem__(self, idx: Tuple[int, int]) -> float: ...
    def __setitem__(self, idx: Tuple[int, int], val: float) -> None: ...

class tns:
    @staticmethod
    def add_vec(a: Vector, b: Vector) -> Vector: ...
    @staticmethod
    def sub_vec(a: Vector, b: Vector) -> Vector: ...
    @staticmethod
    def scl_vec(a: Vector, f: float) -> Vector: ...
    @staticmethod
    def dot_vec(a: Vector, b: Vector) -> float: ...
    @staticmethod
    def add_mat(a: Matrix, b: Matrix) -> Matrix: ...
    @staticmethod
    def sub_mat(a: Matrix, b: Matrix) -> Matrix: ...
    @staticmethod
    def mul(a: Matrix, b: Matrix) -> Matrix: ...

Tensor2d = None
Tensor4d = None
