# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/at0m/Desktop/Tensorium_lib

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/at0m/Desktop/Tensorium_lib

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/at0m/Desktop/Tensorium_lib/CMakeFiles /Users/at0m/Desktop/Tensorium_lib//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/at0m/Desktop/Tensorium_lib/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named intrinsics_gen

# Build rule for target.
intrinsics_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 intrinsics_gen
.PHONY : intrinsics_gen

# fast build rule for target.
intrinsics_gen/fast:
	$(MAKE) $(MAKESILENT) -f Plugins/CMakeFiles/intrinsics_gen.dir/build.make Plugins/CMakeFiles/intrinsics_gen.dir/build
.PHONY : intrinsics_gen/fast

#=============================================================================
# Target rules for targets named vt_gen

# Build rule for target.
vt_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vt_gen
.PHONY : vt_gen

# fast build rule for target.
vt_gen/fast:
	$(MAKE) $(MAKESILENT) -f Plugins/CMakeFiles/vt_gen.dir/build.make Plugins/CMakeFiles/vt_gen.dir/build
.PHONY : vt_gen/fast

#=============================================================================
# Target rules for targets named omp_gen

# Build rule for target.
omp_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 omp_gen
.PHONY : omp_gen

# fast build rule for target.
omp_gen/fast:
	$(MAKE) $(MAKESILENT) -f Plugins/CMakeFiles/omp_gen.dir/build.make Plugins/CMakeFiles/omp_gen.dir/build
.PHONY : omp_gen/fast

#=============================================================================
# Target rules for targets named acc_gen

# Build rule for target.
acc_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 acc_gen
.PHONY : acc_gen

# fast build rule for target.
acc_gen/fast:
	$(MAKE) $(MAKESILENT) -f Plugins/CMakeFiles/acc_gen.dir/build.make Plugins/CMakeFiles/acc_gen.dir/build
.PHONY : acc_gen/fast

#=============================================================================
# Target rules for targets named ARMTargetParserTableGen

# Build rule for target.
ARMTargetParserTableGen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ARMTargetParserTableGen
.PHONY : ARMTargetParserTableGen

# fast build rule for target.
ARMTargetParserTableGen/fast:
	$(MAKE) $(MAKESILENT) -f Plugins/CMakeFiles/ARMTargetParserTableGen.dir/build.make Plugins/CMakeFiles/ARMTargetParserTableGen.dir/build
.PHONY : ARMTargetParserTableGen/fast

#=============================================================================
# Target rules for targets named AArch64TargetParserTableGen

# Build rule for target.
AArch64TargetParserTableGen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AArch64TargetParserTableGen
.PHONY : AArch64TargetParserTableGen

# fast build rule for target.
AArch64TargetParserTableGen/fast:
	$(MAKE) $(MAKESILENT) -f Plugins/CMakeFiles/AArch64TargetParserTableGen.dir/build.make Plugins/CMakeFiles/AArch64TargetParserTableGen.dir/build
.PHONY : AArch64TargetParserTableGen/fast

#=============================================================================
# Target rules for targets named RISCVTargetParserTableGen

# Build rule for target.
RISCVTargetParserTableGen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RISCVTargetParserTableGen
.PHONY : RISCVTargetParserTableGen

# fast build rule for target.
RISCVTargetParserTableGen/fast:
	$(MAKE) $(MAKESILENT) -f Plugins/CMakeFiles/RISCVTargetParserTableGen.dir/build.make Plugins/CMakeFiles/RISCVTargetParserTableGen.dir/build
.PHONY : RISCVTargetParserTableGen/fast

#=============================================================================
# Target rules for targets named TensoriumDispatchPlugin

# Build rule for target.
TensoriumDispatchPlugin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TensoriumDispatchPlugin
.PHONY : TensoriumDispatchPlugin

# fast build rule for target.
TensoriumDispatchPlugin/fast:
	$(MAKE) $(MAKESILENT) -f Plugins/CMakeFiles/TensoriumDispatchPlugin.dir/build.make Plugins/CMakeFiles/TensoriumDispatchPlugin.dir/build
.PHONY : TensoriumDispatchPlugin/fast

#=============================================================================
# Target rules for targets named TensoriumLLVM_IRCheck

# Build rule for target.
TensoriumLLVM_IRCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TensoriumLLVM_IRCheck
.PHONY : TensoriumLLVM_IRCheck

# fast build rule for target.
TensoriumLLVM_IRCheck/fast:
	$(MAKE) $(MAKESILENT) -f Plugins/CMakeFiles/TensoriumLLVM_IRCheck.dir/build.make Plugins/CMakeFiles/TensoriumLLVM_IRCheck.dir/build
.PHONY : TensoriumLLVM_IRCheck/fast

#=============================================================================
# Target rules for targets named test_core_objs

# Build rule for target.
test_core_objs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_core_objs
.PHONY : test_core_objs

# fast build rule for target.
test_core_objs/fast:
	$(MAKE) $(MAKESILENT) -f Tests/CMakeFiles/test_core_objs.dir/build.make Tests/CMakeFiles/test_core_objs.dir/build
.PHONY : test_core_objs/fast

#=============================================================================
# Target rules for targets named test_grid_objs

# Build rule for target.
test_grid_objs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_grid_objs
.PHONY : test_grid_objs

# fast build rule for target.
test_grid_objs/fast:
	$(MAKE) $(MAKESILENT) -f Tests/CMakeFiles/test_grid_objs.dir/build.make Tests/CMakeFiles/test_grid_objs.dir/build
.PHONY : test_grid_objs/fast

#=============================================================================
# Target rules for targets named test_bssn_initial_objs

# Build rule for target.
test_bssn_initial_objs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_bssn_initial_objs
.PHONY : test_bssn_initial_objs

# fast build rule for target.
test_bssn_initial_objs/fast:
	$(MAKE) $(MAKESILENT) -f Tests/CMakeFiles/test_bssn_initial_objs.dir/build.make Tests/CMakeFiles/test_bssn_initial_objs.dir/build
.PHONY : test_bssn_initial_objs/fast

#=============================================================================
# Target rules for targets named test_bssn_constraints_objs

# Build rule for target.
test_bssn_constraints_objs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_bssn_constraints_objs
.PHONY : test_bssn_constraints_objs

# fast build rule for target.
test_bssn_constraints_objs/fast:
	$(MAKE) $(MAKESILENT) -f Tests/CMakeFiles/test_bssn_constraints_objs.dir/build.make Tests/CMakeFiles/test_bssn_constraints_objs.dir/build
.PHONY : test_bssn_constraints_objs/fast

#=============================================================================
# Target rules for targets named test_bssn_ricci_objs

# Build rule for target.
test_bssn_ricci_objs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_bssn_ricci_objs
.PHONY : test_bssn_ricci_objs

# fast build rule for target.
test_bssn_ricci_objs/fast:
	$(MAKE) $(MAKESILENT) -f Tests/CMakeFiles/test_bssn_ricci_objs.dir/build.make Tests/CMakeFiles/test_bssn_ricci_objs.dir/build
.PHONY : test_bssn_ricci_objs/fast

#=============================================================================
# Target rules for targets named test_bssn_solvers_objs

# Build rule for target.
test_bssn_solvers_objs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_bssn_solvers_objs
.PHONY : test_bssn_solvers_objs

# fast build rule for target.
test_bssn_solvers_objs/fast:
	$(MAKE) $(MAKESILENT) -f Tests/CMakeFiles/test_bssn_solvers_objs.dir/build.make Tests/CMakeFiles/test_bssn_solvers_objs.dir/build
.PHONY : test_bssn_solvers_objs/fast

#=============================================================================
# Target rules for targets named TensoriumChiEvolutionDemo

# Build rule for target.
TensoriumChiEvolutionDemo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TensoriumChiEvolutionDemo
.PHONY : TensoriumChiEvolutionDemo

# fast build rule for target.
TensoriumChiEvolutionDemo/fast:
	$(MAKE) $(MAKESILENT) -f Tests/CMakeFiles/TensoriumChiEvolutionDemo.dir/build.make Tests/CMakeFiles/TensoriumChiEvolutionDemo.dir/build
.PHONY : TensoriumChiEvolutionDemo/fast

#=============================================================================
# Target rules for targets named TensoriumGammaEvolutionDemo

# Build rule for target.
TensoriumGammaEvolutionDemo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TensoriumGammaEvolutionDemo
.PHONY : TensoriumGammaEvolutionDemo

# fast build rule for target.
TensoriumGammaEvolutionDemo/fast:
	$(MAKE) $(MAKESILENT) -f Tests/CMakeFiles/TensoriumGammaEvolutionDemo.dir/build.make Tests/CMakeFiles/TensoriumGammaEvolutionDemo.dir/build
.PHONY : TensoriumGammaEvolutionDemo/fast

#=============================================================================
# Target rules for targets named TensoriumTests

# Build rule for target.
TensoriumTests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TensoriumTests
.PHONY : TensoriumTests

# fast build rule for target.
TensoriumTests/fast:
	$(MAKE) $(MAKESILENT) -f Tests/CMakeFiles/TensoriumTests.dir/build.make Tests/CMakeFiles/TensoriumTests.dir/build
.PHONY : TensoriumTests/fast

#=============================================================================
# Target rules for targets named TensoriumTestCore

# Build rule for target.
TensoriumTestCore: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TensoriumTestCore
.PHONY : TensoriumTestCore

# fast build rule for target.
TensoriumTestCore/fast:
	$(MAKE) $(MAKESILENT) -f Tests/CMakeFiles/TensoriumTestCore.dir/build.make Tests/CMakeFiles/TensoriumTestCore.dir/build
.PHONY : TensoriumTestCore/fast

#=============================================================================
# Target rules for targets named TensoriumTestGrid

# Build rule for target.
TensoriumTestGrid: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TensoriumTestGrid
.PHONY : TensoriumTestGrid

# fast build rule for target.
TensoriumTestGrid/fast:
	$(MAKE) $(MAKESILENT) -f Tests/CMakeFiles/TensoriumTestGrid.dir/build.make Tests/CMakeFiles/TensoriumTestGrid.dir/build
.PHONY : TensoriumTestGrid/fast

#=============================================================================
# Target rules for targets named TensoriumTestBSSN

# Build rule for target.
TensoriumTestBSSN: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TensoriumTestBSSN
.PHONY : TensoriumTestBSSN

# fast build rule for target.
TensoriumTestBSSN/fast:
	$(MAKE) $(MAKESILENT) -f Tests/CMakeFiles/TensoriumTestBSSN.dir/build.make Tests/CMakeFiles/TensoriumTestBSSN.dir/build
.PHONY : TensoriumTestBSSN/fast

#=============================================================================
# Target rules for targets named TensoriumBenchmarks

# Build rule for target.
TensoriumBenchmarks: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TensoriumBenchmarks
.PHONY : TensoriumBenchmarks

# fast build rule for target.
TensoriumBenchmarks/fast:
	$(MAKE) $(MAKESILENT) -f Tests/CMakeFiles/TensoriumBenchmarks.dir/build.make Tests/CMakeFiles/TensoriumBenchmarks.dir/build
.PHONY : TensoriumBenchmarks/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... AArch64TargetParserTableGen"
	@echo "... ARMTargetParserTableGen"
	@echo "... RISCVTargetParserTableGen"
	@echo "... acc_gen"
	@echo "... intrinsics_gen"
	@echo "... omp_gen"
	@echo "... vt_gen"
	@echo "... TensoriumBenchmarks"
	@echo "... TensoriumChiEvolutionDemo"
	@echo "... TensoriumDispatchPlugin"
	@echo "... TensoriumGammaEvolutionDemo"
	@echo "... TensoriumLLVM_IRCheck"
	@echo "... TensoriumTestBSSN"
	@echo "... TensoriumTestCore"
	@echo "... TensoriumTestGrid"
	@echo "... TensoriumTests"
	@echo "... test_bssn_constraints_objs"
	@echo "... test_bssn_initial_objs"
	@echo "... test_bssn_ricci_objs"
	@echo "... test_bssn_solvers_objs"
	@echo "... test_core_objs"
	@echo "... test_grid_objs"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

